---
# Variable to enable container pre-setup tasks, set to true to run containers on a system.
containers: false

podman_user: seal
podman_user_uid: 11111
podman_auto_update_schedule: "*:0/5"

###########################################
# defaults for freeradius_container ######
# ########################################
## Run freeradius container tasks on host
freeradius_container: no

## Set the freeradius image

freerad_image: docker.io/freeradius/freeradius-server:latest

###########################################
##### Password Reset Tool Container #######
###########################################
password_reset_container: no
password_reset_container_image: docker.io/ltbproject/self-service-password:latest

password_reset_port: 8085

###########################################
##### IT Tools Container ##################
###########################################
it_tools_container: false
it_tools_port: 8080
it_tools_container_image: docker.io/corentinth/it-tools:latest


###########################################
##### Worpress Pod ########################
###########################################
wordpress_image: docker.io/wordpress:latest
mysql_image: docker.io/mysql:latest

###########################################
##### Cloudflared #########################
###########################################
cloudflared_container_image: docker.io/cloudflare/cloudflared:latest

###########################################
##### Zot #################################
###########################################
zot_image: ghcr.io/project-zot/zot:latest

###########################################
##### Hugo ################################
###########################################
hugosite_image: dt-lab3:5000/lrsite
hugosite_port: 8090

