#SPDX-License-Identifier: MIT-0
---
- block:

  - import_tasks: pre.yml
    tags: pre
  - import_tasks: it-tools.yml
  - block:
      - include_tasks: wordpress_pod.yml
        loop: "{{ wordpress_sites | default([]) }}"
    when:
      - wordpress_pod
      - wordpress_sites is defined
    tags: wordpress_pod
  - block:
      - include_tasks: zot-container.yml
    when:
      - zot_container
    tags: zot_container
  - block:
      - include_tasks: hugo.yml
    when:
      - hugosite
    tags:
      - hugosite

  tags: containers
  when: containers

