#SPDX-License-Identifier: MIT-0
---
- block:

  - import_tasks: pre.yml
    tags: pre
  - import_tasks: it-tools.yml
  - block:
      - include_tasks: wordpress_pod.yml
        loop: "{{ wordpress_sites | default([]) }}"
    when:
      - wordpress_pod
      - wordpress_sites is defined
    tags: wordpress_pod

  tags: containers
  when: containers

