---
- block:
  - name: Allow {{ password_reset_port }} on the firewall
    ansible.posix.firewalld:
      port: "{{ password_reset_port }}/tcp"
      permanent: true
      state: enabled
      immediate: true

  - name: Pull password reset container image
    containers.podman.podman_image:
      name: "{{ password_reset_container_image }}"
      state: present

  - name: Create reset directory
    file:
      path: /home/{{ podman_user }}/reset
      state: directory
      mode: '0755'
      owner: "{{ podman_user }}"
      group: "{{ podman_user }}"

  - name: Copy php config to host
    template:
      src: config.inc.local.php.j2
      dest: /home/{{ podman_user }}/reset/config.inc.local.php
    
  - name: Copy psi-logo.jpg to host
    copy:
      src: psi-logo.png
      dest: /home/{{ podman_user }}/reset/
      mode: '0644'
    notify: daemon reload

  - name: Set SELinux context for /reset
    community.general.sefcontext:
      target: '/home/{{ podman_user }}/reset(/.*)?'
      setype: container_file_t
      state: present

  - name: restorecon
    command: restorecon -Rv /home/{{ podman_user }}/reset

  - name: Add the quadlet file
    template:
      src: password-reset.j2
      dest: /etc/containers/systemd/users/{{ podman_user }}/password-reset.container
    notify: daemon reload

  - name: daemon reload
    become: true
    become_user: "{{ podman_user }}"
    ansible.builtin.systemd_service:
      daemon_reload: true
      scope: user
    environment:
      XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"

  - name: Run Quadlet
    become: true
    become_user: "{{ podman_user }}"
    ansible.builtin.systemd_service:
      name: password-reset.service
      state: restarted
      enabled: true
      scope: user
    environment:
      XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"

  when: password_reset_container
  tags: password_reset_container
