## Use `sudo -u {{ podman_user }} bash -li` to login as nologin user.
- name: Make sure rootless user exists to run containers
  user:
    name: "{{ podman_user }}"
    uid: "{{ podman_user_uid }}"
    password: "{{ podman_user_password }}"
    create_home: yes
    shell: /bin/bash
    state: present

- name: Enable linger for {{ podman_user }}
  command: loginctl enable-linger {{ podman_user }}
  become: yes
    
- name: Create Quadlet Directory
  file:
    path: /etc/containers/systemd/users/{{ podman_user }}
    state: directory
    mode: '0755'

- name: Enable podman socket
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd_service:
    name: podman.socket
    state: started
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"

- name: Add custom registries.conf 
  template:
     src: registries.conf.j2
     dest: /etc/containers/registries.conf
     owner: root
     group: root
     mode: '0644'

- name: Create podman-auto-update timer override directory
  ansible.builtin.file:
    path: /home/{{ podman_user }}/.config/systemd/user/podman-auto-update.timer.d
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "0755"

- name: Add podman-auto-update timer override
  ansible.builtin.template:
    src: podman-auto-update-timer-override.conf.j2
    dest: /home/{{ podman_user }}/.config/systemd/user/podman-auto-update.timer.d/override.conf
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "0644"
  notify: Reload and restart podman-auto-update timer

- name: Enable podman auto-update timer
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    state: started
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"

- name: Add registry credentials for {{ podman_user }}
  template:
    src: auth.json.j2
    dest: /run/user/{{ podman_user_uid }}/containers/auth.json
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "0644"
