# -------------------------------
# QEMU Guest Agent Install
# -------------------------------

- block:
  - name: Install QEMU Agent
    package:
      name: qemu-guest-agent
      state: present

  - name: Enable and restart QEMU agent
    service:
      name: qemu-guest-agent
      state: restarted
      enabled: yes
  
  when:
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type in ["kvm", "qemu"]
    - qemu_config
  tags: qemu_config
  